### ISSUE TITLE
Insertion tool: When the branch name of the source repo is long, it fails with a path too long error.

### ISSUE THREAD

**Issue by peterwald** [dotnet/roslyn-tools#1200]
This is the relevant section from the logs. Source branch name is **locfiles/1ac4d703-ca45-454b-85e0-ee25ef6645f3-on-dev17.2.x**

```
2022-04-04T16:05:33.3171013Z Getting latest passing build for project DevDiv, queue VSUnitTesting-Signed, and branch locfiles/1ac4d703-ca45-454b-85e0-ee25ef6645f3-on-dev17.2.x
2022-04-04T16:05:34.0789998Z Found VSUnitTesting-Signed build number 20220404.5
2022-04-04T16:05:34.3217879Z Downloading artifacts to C:\Users\cloudtest\AppData\Local\Temp\VS_Unit_Testinglocfiles_1ac4d703-ca45-454b-85e0-ee25ef6645f3-on-dev17.2.x\20220404.5
2022-04-04T16:06:42.8304995Z ##[error] System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
2022-04-04T16:06:42.8312625Z    at System.IO.PathHelper.GetFullPathName()
2022-04-04T16:06:42.8313045Z    at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
2022-04-04T16:06:42.8313416Z    at System.IO.Path.GetFullPathInternal(String path)
2022-04-04T16:06:42.8313782Z    at System.IO.Compression.ZipFileExtensions.ExtractToDirectory(ZipArchive source, String destinationDirectoryName)
2022-04-04T16:06:42.8314201Z    at Roslyn.Insertion.RoslynInsertionTool.<DownloadBuildArtifactsAsync>d__51.MoveNext()
2022-04-04T16:06:42.8314552Z --- End of stack trace from previous location where exception was thrown ---
2022-04-04T16:06:42.8315905Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-04-04T16:06:42.8316265Z    at Roslyn.Insertion.RoslynInsertionTool.<GetInsertionArtifactsAsync>d__50.MoveNext()
2022-04-04T16:06:42.8316616Z --- End of stack trace from previous location where exception was thrown ---
2022-04-04T16:06:42.8316944Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2022-04-04T16:06:42.8317320Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2022-04-04T16:06:42.8317709Z    at Roslyn.Insertion.RoslynInsertionTool.<PerformInsertionAsync>d__13.MoveNext()
2022-04-04T16:06:42.9699825Z ##[error]PowerShell exited with code '1'.
```

/cc @AbhitejJohn

**Comment by RikkiGibson** [comment]
Consider linking to the failing run. Perhaps it would be possible to enable long paths.

**Comment by peterwald** [comment]
Here is the failed release: https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-environment-logs&releaseId=1303753&environmentId=6675583

**Comment by peterwald** [comment]
@RikkiGibson We are still running into this on branches that aren't particularly long. In this case `dev/pewaldsc/perf-telem-on-dev17.2.x`

https://devdiv.visualstudio.com/DevDiv/_releaseProgress?_a=release-environment-logs&releaseId=1317229&environmentId=6754121&jobTimelineRecordIdToSelect=92dda6ce-ecf4-5b59-42ed-f60b022ddf4c&selectTaskWithIndex=5#

**Comment by AbhitejJohn** [comment]
How do we want to enable long paths? Seems like we'd need to modify the registry based on [this](https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd). I wonder if we could get away with most of these cases by shortening the base path we download these artifacts to. That seems pretty long at the moment.

**Comment by JoeRobich** [comment]
Seems like the easiest fix here would be to use a guid for the temp folder name instead of the branchname. We wouldn't be able to cleanup old artifacts that happen to be on the vm, but we shouldn't be responsible in the first place.

https://github.com/dotnet/roslyn-tools/blob/99f722967d1af9674a667bd5d764d29fff009d9e/src/RoslynInsertionTool/RoslynInsertionTool/RoslynInsertionTool.VisualStudioTeamServices.cs#L396-L407

**Comment by AbhitejJohn** [comment]
@JoeRobich : That makes sense, thanks for fixing that up!
