### ISSUE TITLE
Failing to fetch builds in case of 1ES PT build

### ISSUE THREAD

**Issue by jakubch1** [dotnet/roslyn-tools#1389]
1ES PT build is produced always from 2 repos and 2 branches:

![image](https://github.com/dotnet/roslyn-tools/assets/59966772/be747291-75f7-428d-8dc9-3e5de09ca043)

then insertion tool is not able to find this builds:
```
2024-03-05T09:59:48.3839400Z Getting latest passing build for project DevDiv, queue vs-code-coverage-ci, and branch dev/jachocho/pr_to_1espt_2
2024-03-05T09:59:49.3198766Z ##[error] System.IO.IOException: Unable to get latest build for 'vs-code-coverage-ci' from project 'DevDiv' in ''
2024-03-05T09:59:49.3206905Z    at Roslyn.Insertion.RoslynInsertionTool.<GetLatestPassedComponentBuildAsync>d__44.MoveNext()
2024-03-05T09:59:49.3207505Z --- End of stack trace from previous location where exception was thrown ---
2024-03-05T09:59:49.3207775Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2024-03-05T09:59:49.3208074Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2024-03-05T09:59:49.3208465Z    at Roslyn.Insertion.RoslynInsertionTool.<PerformInsertionAsync>d__13.MoveNext()
```
https://devdiv.visualstudio.com/devDiv/_releaseProgress?_a=release-environment-logs&releaseId=1515333&environmentId=8292782

Any idea how branchName should be specified in this case? Is this even supported?

**Comment by jakubch1** [comment]
I found that issue is that 1ES PT is generating artifacts in different way. Fetching by branch name still works.
